# Generated by Django 2.2.5 on 2019-09-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('subtitle', models.CharField(default='', max_length=255)),
                ('topic', models.CharField(default='', max_length=100)),
                ('image', models.CharField(default='', max_length=255)),
                ('author', models.CharField(default='', max_length=100)),
                ('content', models.TextField(default='')),
            ],
        ),
    ]
