# Generated by Django 2.2.5 on 2019-09-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertise',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='advertise',
            name='slug',
            field=models.CharField(default='', max_length=100),
        ),
    ]
