# Generated by Django 2.2.5 on 2019-09-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(default='', max_length=100)),
                ('username', models.CharField(default='', max_length=100, unique=True)),
                ('password', models.CharField(default='', max_length=100)),
                ('phone_number', models.CharField(default='', max_length=15)),
                ('email', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=255)),
                ('date_of_birth', models.DateTimeField()),
            ],
        ),
    ]
