# Generated by Django 2.2.5 on 2019-09-27 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20190927_1334'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carousel',
        ),
    ]
