# Generated by Django 2.2.5 on 2019-09-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_delete_carousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='tag',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Hot')], default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
