# Generated by Django 2.2.5 on 2019-09-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.IntegerField(choices=[(0, 'Cash'), (1, 'Visa | Mastercard'), (2, 'Digital Wallet')], default=0),
        ),
    ]
